/**
 * 样式定义模块
 */
import type { CSSProperties } from 'react';

export const viewerStyles: Record<string, CSSProperties> = {
  container: {
    width: '100%',
    height: '100%',
    boxSizing: 'border-box',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 320px',
    columnGap: 0,
    color: '#fff',
    overflow: 'hidden',
  },
  main: {
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 28px 80px rgba(0,0,0,0.55)',
    minHeight: 0,
  },
  mainBackdrop: {
    position: 'absolute',
    inset: 0,
  },
  mainContent: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    padding: 0,
    minHeight: 0,
    minWidth: 0,
  },
  viewer: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 24px 60px rgba(0,0,0,0.5)',
    touchAction: 'none',
    minHeight: 0,
  },
  controls: {
    position: 'absolute',
    bottom: 16,
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    gap: 16,
    padding: '8px 18px',
    borderRadius: 24,
    alignItems: 'center',
  },
  scaleBadge: {
    position: 'absolute',
    bottom: 64,
    left: 16,
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    letterSpacing: 0.2,
  },
  filmstripShell: {
    marginTop: 0,
    padding: '3px 12px',
    boxShadow: '0 16px 42px rgba(0,0,0,0.52)',
  },
  filmstrip: {
    display: 'flex',
    overflowX: 'auto',
    gap: 12,
    paddingBottom: 4,
  },
  sidePanel: {
    boxShadow: '0 28px 80px rgba(0,0,0,0.55)',
    padding: '20px 24px',
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
    minHeight: 0,
  },
  histogramCard: {
    padding: '12px 12px 18px',
    background: 'rgba(0,0,0,0.34)',
    borderRadius: 0,
  },
  viewerCloseWrap: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 2,
  },
  viewerClose: {
    color: '#fff',
    background: 'rgba(0,0,0,0.4)',
    border: '1px solid rgba(255,255,255,0.25)',
    boxShadow: '0 8px 18px rgba(0,0,0,0.45)',
    borderRadius: '100%',
    width: 32,
    height: 32,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
};

