from __future__ import annotations

from typing import Dict, List, Optional, Protocol

from domain.ai.entities import AIDefaultModelEntity, AIModelEntity, AIProviderEntity


class AIRepository(Protocol):
    async def list_providers(self) -> List[AIProviderEntity]: ...

    async def get_provider(self, provider_id: int) -> AIProviderEntity | None: ...

    async def create_provider(self, data: Dict) -> AIProviderEntity: ...

    async def update_provider(self, provider_id: int, data: Dict) -> AIProviderEntity: ...

    async def delete_provider(self, provider_id: int) -> None: ...

    async def list_models(self, provider_id: int) -> List[AIModelEntity]: ...

    async def get_model(self, model_id: int) -> AIModelEntity | None: ...

    async def create_model(self, provider_id: int, data: Dict) -> AIModelEntity: ...

    async def update_model(self, model_id: int, data: Dict) -> AIModelEntity: ...

    async def delete_model(self, model_id: int) -> None: ...

    async def list_default_models(self) -> List[AIDefaultModelEntity]: ...

    async def set_default_model(self, ability: str, model_id: Optional[int]) -> None: ...

    async def get_default_model(self, ability: str) -> AIModelEntity | None: ...

    async def get_model_by_name(self, provider_id: int, name: str) -> AIModelEntity | None: ...


__all__ = ["AIRepository"]
